# vim: ft=tmux

set -s escape-time 0
set -g history-limit 64000
set -g display-time 4000
set -g assume-paste-time 0
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-features ",xterm-256color:RGB"
set -g extended-keys-format csi-u

set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on

set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

set -g allow-passthrough on
set -wg allow-rename on
set -g extended-keys on
set -g remain-on-exit on

set -g update-environment "TMUX_DIR TMUX_SESSIONS_DIR SSH_AUTH_SOCK SSH_ASKPASS WINDOWID SSH_CONNECTION XAUTHORITY"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

