# vim: ft=tmux

set -g mode-style "fg=#{@cl_base8},bg=#{@cl_yellow3}"
set -g message-style "fg=#{@cl_base9},bg=#{@cl_base3}"

set -g pane-border-style "fg=#{@cl_base3}"
set -g pane-active-border-style "fg=#{@cl_yellow2}"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#{@cl_base4},bg=#{@cl_base3}"

set -gF status-bg "#{@cl_base2}"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g @sepl ""
set -g @sepr ""

set -g @section_ses "#[fg=#{@cl_base1},bg=#{@cl_base8},bold] #S:#I #[fg=#{@cl_base8},bg=#{@cl_base6}]#{@sepr}"
set -g @section_user "#[fg=#{@cl_base1},bg=#{@cl_base7},bold] #(whoami)#[fg=#{@cl_base7},bg=#{@cl_base2}]"
set -g status-left "#{E:@section_ses}#{E:@section_user} "

set -g @section_clock "#[fg=#{@cl_base7},bg=#{@cl_base2}]#{@sepl}#[fg=#{@cl_base1},bg=#{@cl_base7},bold] %H:%M "
set -g @section_host "#[fg=#{@cl_base8},bg=#{@cl_base7}]#{@sepl}#[fg=#{@cl_base1},bg=#{@cl_base8},bold] #h "
set -g status-right "#{E:@section_clock}#{E:@section_host}"

setw -g window-status-activity-style "underscore,fg=#839496,bg=#002b36"
setw -g window-status-style "NONE,fg=#839496,bg=#002b36"
setw -gF window-status-separator "#[bg=#{@cl_cyan1}]"

set -g @win_start_active "#[fg=#{@cl_cyan1},bg=#{?window_start_flag,#{@cl_base2},#{@cl_cyan1}}]"
set -g @win_end_active "#[fg=#{@cl_cyan1},bg=#{?window_end_flag,#{@cl_base2},#{@cl_cyan1}}]"
set -g @inactive_win_idx "#{E:@win_start_active}#[fg=#{@cl_base6},bg=#{@cl_cyan1}] #I #[fg=#{@cl_base5}]-"
set -g @inactive_win_name "#[fg=#{@cl_base6},bg=#{@cl_cyan1}] #{b:window_name} #{E:@win_end_active}"
setw -gF window-status-format '#{@inactive_win_idx}#{@inactive_win_name}'

set -g @win_start_inactive "#[fg=#{@cl_base8},bg=#{?window_start_flag,#{@cl_base2},#{@cl_cyan1}}]"
set -g @win_end_inactive "#[fg=#{@cl_yellow3},bg=#{?window_end_flag,#{@cl_base2},#{@cl_cyan1}}]"
set -g @active_win_idx "#{E:@win_start_inactive}#[fg=#{@cl_yellow3},bg=#{@cl_base8}] #I #[fg=#{@cl_base8},bg=#{@cl_yellow3}]"
set -g @active_win_name "#[fg=#{@cl_base9},bg=#{@cl_yellow3}] #{b:window_name} #{E:@win_end_inactive}"
setw -gF window-status-current-format '#{@active_win_idx}#{@active_win_name}' 
