# vim: ft=tmux

# base
set -g @cl_base1 "#001419"
set -g @cl_base2 "#012B36"
set -g @cl_base3 "#063642"
set -g @cl_base4 "#586E75"
set -g @cl_base5 "#667C83"
set -g @cl_base6 "#9FABAD"
set -g @cl_base7 "#ADB8B8"
set -g @cl_base8 "#EEE8D5"
set -g @cl_base9 "#FDF6E3"
set -g @cl_base10 "#FFFFFF"

# yellow
set -g @cl_yellow1 "#332700"
set -g @cl_yellow2 "#664D00"
set -g @cl_yellow3 "#B58901"
set -g @cl_yellow4 "#FFC002"
set -g @cl_yellow5 "#FDE999"

# orange
set -g @cl_orange1 "#5C2208"
set -g @cl_orange2 "#A13C11"
set -g @cl_orange3 "#CB4A15"
set -g @cl_orange4 "#F7530E"
set -g @cl_orange5 "#FF9568"

# red
set -g @cl_red1 "#57110F"
set -g @cl_red2 "#B7211E"
set -g @cl_red3 "#DB322E"
set -g @cl_red4 "#F5524F"
set -g @cl_red5 "#FF9B9D"

# magenta
set -g @cl_magenta1 "#541132"
set -g @cl_magenta2 "#B02668"
set -g @cl_magenta3 "#D43682"
set -g @cl_magenta4 "#F255A1"
set -g @cl_magenta5 "#FF77B9"

# violet
set -g @cl_vioelt1 "#26285B"
set -g @cl_vioelt2 "#494FB6"
set -g @cl_vioelt3 "#6C71C5"
set -g @cl_vioelt4 "#9EA0ED"
set -g @cl_vioelt5 "#CACFFF"

# blue
set -g @cl_blue1 "#103955"
set -g @cl_blue2 "#1A6397"
set -g @cl_blue3 "#258BD2"
set -g @cl_blue4 "#48ADF5"
set -g @cl_blue5 "#AADCFF"

# cyan
set -g @cl_cyan1 "#113B3E"
set -g @cl_cyan2 "#196165"
set -g @cl_cyan3 "#2AA198"
set -g @cl_cyan4 "#28EDE0"
set -g @cl_cyan5 "#B9FFFB"

# green
set -g @cl_green1 "#2C3200"
set -g @cl_green2 "#5A6601"
set -g @cl_green3 "#859A00"
set -g @cl_green4 "#BBFB00"
set -g @cl_green5 "#D6FFAD"
