 set -g @tpm_plugins '             \
   tmux-plugins/tpm                \
   omerxx/tmux-sessionx            \
'

source ~/.config/tmux/theme.conf
source ~/.config/tmux/options.conf
source ~/.config/tmux/keymaps.conf
source ~/.config/tmux/statusline.conf

run ~/.config/tmux/plugins/tpm/tpm

